#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'pages/projects.html'}
- {name: 'Portfolio', url: 'pages/blog.html'}
- {name: 'Résumé', url: 'pages/about.html'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a Computer Science and Political Science student at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/bio-photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  Driven Computer Science and Political Science student at the University of Massachusetts Amherst. Excited about the intersectionality of Computer Science and Politics to create a better world. Especially interested in AI and machine learning ethics, data privacy, mobile computing, and human interface design, as well as advocacy around social, racial, educational, and environmental justice. 

contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Beton3', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'UMass BRUT', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'UMass Campus Architecture', folder: 'proj-3', file: 'projects/proj-3.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/adam-lechowicz-58703a154/'}
- {icon: 'twitter', link: 'https://twitter.com/adamlechowicz'}
- {icon: 'instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'envelope', link: 'mailto:adamlechowicz921@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
