#-------------------------------
# General Site Settings

menu:
- {name: 'Research', url: 'publications'}
- {name: 'Blog', url: 'blog'}
- {name: 'CV', url: 'AdamLechowiczCurriculumVitae.pdf'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a computer science doctoral candidate at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'
  og:image: '/assets/img/5x3.jpg'
  og:description: 'Adam Lechowicz is a computer science doctoral candidate at the University of Massachusetts Amherst.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-135296285-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <a href="https://www.umass.edu"><img src="/assets/img/5x3.jpg" align="right" alt="Campus of UMass Amherst" style="width: 47.8%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"/></a> 
  <!-- <a href="https://www.nrel.gov"><img src="/assets/img/5x3nrel.jpeg" align="right" alt="ESIF Building at the National Renewable Energy Laboratory" style="width: 47.8%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"/></a> -->
  <img src="/assets/img/bio_photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"/>
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  #### Adam Lechowicz
  
  ***he/they***
  
  <p class="small" style="font-variant:small-caps">
  </p>

  I am a fourth-year Ph.D. candidate in the [Manning College of Information and Computer Sciences](https://www.cics.umass.edu) at the University of Massachusetts Amherst, advised by [Mohammad Hajiesmaili](https://groups.cs.umass.edu/hajiesmaili/) and [Prashant Shenoy](https://people.cs.umass.edu/~shenoy/index.html).  
  
  <p class="small" style="font-variant:small-caps">
  </p>

  <p style="text-align:center; font-weight: bolder; font-size: 16px;"><i> sustainability for computing, computing for sustainability </i></p>

  <p class="small" style="font-variant:small-caps">
  </p>
  
  I work at the intersection of theory and systems, with an emphasis on emerging problems in energy and sustainability.  From a theoretical perspective, I am interested in decision-making under uncertainty, particularly using the learning-augmented algorithms framework, which combines the provable guarantees of traditional algorithm design with AI-driven performance.  On the application side, I am interested in novel system designs that increase the flexibility, efficiency, and sustainability of energy systems or computing infrastructure. My work is supported by a [U.S. Department of Energy Computational Science Graduate Fellowship (CSGF)](https://www.krellinst.org/csgf/about-doe-csgf).

  <p class="small" style="font-variant:small-caps">
  </p>

  In Summer 2024, I worked with [Joshua Comden](https://research-hub.nrel.gov/en/persons/joshua-comden) at the [National Renewable Energy Laboratory](https://www.nrel.gov) on incentives and human-driven uncertainties in energy systems.  
  Before my Ph.D., I completed my undergraduate thesis with [Cameron Musco](https://people.cs.umass.edu/~cmusco/), studying polarization in social networks.

  <p class="small" style="font-variant:small-caps">
  </p>
  
  <!-- <p style="margin-bottom: 5px !important;">Through my research, I strive to advance ideals of social, racial, economic, and environmental justice.</p> -->
  
  email: alechowicz [at] umass [dot] edu

  <div style="display: flex;">
  <div>
    <h4 id="selected-publications" style="margin-bottom:0.5em;">Selected Publications</h4>
  </div>
  <em style="margin-top: auto; margin-left: auto; margin-bottom: 0.85em; margin-right: 0.75em;"><a href="publications.html">full list →&nbsp;</a></em>
  </div>

  **[Learning-Augmented Competitive Algorithms for Spatiotemporal Online Allocation with Deadline Constraints](https://arxiv.org/abs/2408.07831)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Bo Sun, Noman Bashir, <span class="more-authors" style="border-bottom: 1px dashed" title="" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '3 more authors' ? 'Mohammad Hajiesmaili, Adam&nbsp;Wierman, Prashant Shenoy' : '3 more authors'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">3 more authors</span> <br/>
  ACM SIGMETRICS 2025.
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  **[Optimizing Individualized Incentives from Grid Measurements and Limited Knowledge of Agent Behavior](https://arxiv.org/abs/2410.14936)**  <br/>
  Adam Lechowicz, Joshua Comden, Andrey Bernstein<br/>
  ACM e-Energy 2025.
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  **[Chasing Convex Functions with Long-term Constraints](https://arxiv.org/abs/2402.14012)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Bo Sun, Noman Bashir, <span class="more-authors" style="border-bottom: 1px dashed" title="" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '3 more authors' ? 'Mohammad Hajiesmaili, Adam&nbsp;Wierman, Prashant Shenoy' : '3 more authors'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">3 more authors</span> <br/>
  ICML 2024. ([workshop version](https://learning-augmented-algorithms.github.io/2024/papers/sigmetrics24-lata-posters-paper4.pdf))

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[The Online Pause and Resume Problem: <br/> *Optimal Algorithms and An Application to Carbon-aware Load Shifting*](https://arxiv.org/abs/2303.17551)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Jinhang Zuo, Noman Bashir, <span class="more-authors" style="border-bottom: 1px dashed" title="" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '3 more authors' ? 'Mohammad Hajiesmaili, Adam&nbsp;Wierman, Prashant Shenoy' : '3 more authors'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">3 more authors</span> <br/>
  ACM SIGMETRICS / IFIP Performance 2024.
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  **[Time Fairness in Online Knapsack Problems](https://arxiv.org/abs/2305.13293)**  <br/>
  Adam Lechowicz, Rik Sengupta, Bo Sun, Shahin Kamali, Mohammad Hajiesmaili <br/>
  ICLR 2024. ([workshop version](https://learning-augmented-algorithms.github.io/2023/papers/sigmetrics23-lata-posters-paper8.pdf))

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[Equitable Network-aware Decarbonization of Residential Heating at City Scale](https://arxiv.org/abs/2301.04747)**  <br/>
  Adam Lechowicz, Noman Bashir, John Wamburu, Mohammad Hajiesmaili, Prashant Shenoy  <br/>
  ACM e-Energy 2023. ([slides](https://drive.google.com/file/d/15THywHT1sZXHZGaaIW3LfboftIIu1gnj/view?usp=sharing))

  <div style="display: flex;">
  <div>
    <h4 id="news" style="margin-bottom:0.5em;">Recent News</h4>
  </div>
  <em style="margin-top: auto; margin-left: auto; margin-bottom: 0.85em; margin-right: 0.75em;"><a href="news.html">more news →&nbsp;</a></em>
  </div>

  - **(October 27th, 2025)** I am at the INFORMS Annual Meeting in Atlanta, GA this week!  I'll be giving an invited talk on [learning-augmented algorithms for spatiotemporal online allocation with deadline constraints](https://submissions.mirasmart.com/InformsAnnual2025/Itinerary/PresentationDetail.aspx?evdid=2627) in the [Algorithms for Grid Integration of AI](https://submissions.mirasmart.com/InformsAnnual2025/Itinerary/EventDetail.aspx?evt=1345) session.  See my slides [here](https://drive.google.com/file/d/1rbBkBUCwowlAGhMvxDA8RDkWHGF7MF8_/view?usp=sharing).

  - **(September 9th, 2025)** I am at the ACM SIGCOMM conference in Coimbra, Portugal this week!  I'll be presenting our short paper on [carbon- and precedence-aware scheduling for data processing](https://arxiv.org/abs/2502.09717) in the SIGCOMM Shorts session.

  - **(July 2nd, 2025)** I am at the INFORMS APS conference at Georgia Tech this week!  I'll be giving an invited talk on [online optimization with switching costs and long-term constraints](https://arxiv.org/abs/2402.14012) in the Learning-Augmented Online Optimization session.

  - **(June 20th, 2025)** I am at ACM e-Energy in Rotterdam, Netherlands this week!  We have two papers on [optimizing individualized incentives with unknown agent behavior](https://dl.acm.org/doi/10.1145/3679240.3734594) and [the carbon cost of residential solar](https://dl.acm.org/doi/10.1145/3679240.3734603).
  
  - **(June 12th, 2025)** I am at the ACM SIGMETRICS conference at Stony Brook University this week!  I'll be presenting our paper on [spatiotemporal online allocation with deadline constraints](https://dl.acm.org/doi/10.1145/3711701) in the Online Learning II session.  I am also co-organizing the [LATA](https://learning-augmented-algorithms.github.io) and [CarbonMetrics](https://noman-bashir.github.io/CarbonMetrics/) workshops. 
  
  - **(May 8th, 2025)** I am giving an invited talk at the RSRG / FALCON group meeting at Caltech.  See my slides [here](https://drive.google.com/file/d/1Z6ypQdUXYm4QoVHN88GcbdkKgjWDNpU3/view?usp=share_link).  

  - **(April 29th, 2025)** Our paper on [dynamic incentive allocation for deep decarbonization](https://arxiv.org/abs/2502.08877) was accepted to the ACM Journal on Computing and Sustainable Societies (JCSS)!

  - **(September 3rd, 2024)** I am at the [Seventh Workshop on Autonomous Energy Systems](https://www.nrel.gov/grid/seventh-workshop-autonomous-energy-systems.html) in Golden, CO to present my work on incentives in distribution grids.  
            

#-------------------------------
# Work Section

projects:
- {name: ' ', folder: 'proj-6', file: 'projects/venti.html'}
- {name: ' ', folder: 'proj-5', file: 'projects/backtrack.html'}
# - {name: ' ', folder: 'proj-2', file: 'projects/urv.html'}
- {name: ' ', folder: 'proj-7', file: 'projects/umasstour.html'}
- {name: ' ', folder: 'proj-1', file: 'projects/beton.html'}
- {name: ' ', folder: 'proj-3', file: 'projects/uca.html'}
# - {name: ' ', folder: 'port', file: 'pages/portfolio.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'fa-brands fa-google-scholar', link: 'https://scholar.google.com/citations?user=fZ2-jm0AAAAJ&hl=en&oi=ao'}
- {icon: 'fa-brands fa-linkedin-in', link: 'https://www.linkedin.com/in/adamlechowicz'}
- {icon: 'fa-brands fa-instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'fa-brands fa-x-twitter', link: 'https://x.com/adamlechowicz/'}
- {icon: 'fa-brands fa-github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'fa-solid fa-envelope', link: 'mailto:alechowicz@umass.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
