#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'pages/projects.html'}
- {name: 'Portfolio', url: 'pages/portfolio.html'}
- {name: 'Résumé', url: 'Adam%20Lechowicz%20Résumé.pdf'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a computer science and political science student at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'
  og:image: '/assets/img/500x300.png'
  og:description: 'Adam Lechowicz is a computer science and political science student at the University of Massachusetts Amherst.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/500x300.png" align="right" alt="Old Chapel at UMass Amherst" style="width: 45.2%;"/>
  <img src="/assets/img/bio-photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  #### Adam Lechowicz
  
  **Computer Science and Political Science Student**
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  Hello, my name is Adam, and I'm an undergraduate computer science and political science student at the University of Massachusetts Amherst.  I'm excited about the potential to create a better world through research at the intersection of computer science and public policy. Especially interested in AI, machine learning, ethics, mobile computing, human-computer interaction, and economics, building on ideals of social, racial, educational, and environmental justice. 
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  email: **[alechowicz@umass.edu](mailto:alechowicz@umass.edu)**    <br/>
  phone: **[+1 (774) 994-6908](tel:17749946908)**    <br/>
  linkedin: **[Adam Lechowicz on LinkedIn](https://www.linkedin.com/in/adamlechowicz/)**
  
portfolio: >
  A selected collection of my graphic design work.
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  ## UMass Student Government Association Branding Guide
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/sgastyleguide.png" alt="SGA Style Guide" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  A comprehensive branding guide created for the UMass Student Government Association in Fall 2020.  Designed in parallel with university brand guidelines, I constructed a graphic identity for the organization that uses color and type to implicitly associate the SGA with the university, while still maintaining an independently professional look and feel.
  
  <p><a href="https://adamlechowicz.github.io/UMass%20SGA%20Branding%20Guide.pdf">See the Branding Guide></a></p>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  ## @umass Instagram Story Funding Sheets
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/funding3.png" alt="Instagram Story Sheet" style="width: 45%;"/>
  <img src="/assets/img/portfolio/funding5.png" align="right" alt="Instagram Story Sheet" style="width: 45%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  A collection of informational sheets published on the @umass Instagram story in February 2020.  Designed in harmony with university brand guidelines, I made use of a subtle gradient centered on the university maroon color, in conjunction with the official typeface Frutiger and an assortment of background patterns to create sheets that are clearly related, but not entirely monotonous and "cookie-cutter". 
  
  <p><a href="stories.html">See more Story Sheets ></a></p>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  ## UMass Dorm Icons
  
  <img src="/assets/img/portfolio/brett.png" align="center" alt="An icon of Brett House at UMass" style="width: 90%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  An assortment of simple, distilled icons that depict dormitory buildings on the UMass Amherst campus.  Designing these, I constrained myself by using a low-res pixel art format, shedding extraneous features and focusing on distinctive features that make each building recognizable.  After a base image constructed in pixel-art, I scaled up the image to add color, shadow, and replace jagged roofline edges with smooth diagonal lines, resulting in crisp, simple icons.

  <img src="/assets/img/portfolio/greenough.png" align="center" alt="An icon of Greenough House at UMass" style="width: 90%;"/>

  <p><a href="dorms.html">See more Dorm Icons ></a></p>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  ## Student Government Association Work
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  Loosely organized work that I've completed for the Student Government Association throughout my tenure as a Senator and Secretary of Technology.
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  <img src="/assets/img/portfolio/ucardposter.png" align="center" alt="A poster telling students to vote." style="width: 60%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/splash.png" align="center" alt="A title image" style="width: 80%;"/>
  
  <p><a href="sgawork.html">See more SGA Work ></a></p>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  ## Drawings
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  A small collection of detailed drawings of locations across the UMass campus, completed digitally in Photoshop.

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/bakerdrawing.png" align="center" alt="A drawing of Baker House at UMass" style="width: 80%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/studentunion.png" align="center" alt="A drawing of the Student Union at UMass" style="width: 80%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <p><a href="drawings.html">See more Drawings ></a></p>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  ## Miscellaneous Work

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/pantone.png" alt="Instagram Story Sheet" style="width: 32%;"/>
  <img src="/assets/img/portfolio/helvumb.png" align="right" alt="Instagram Story Sheet" style="width: 62%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  Some additional, completely unorganized work that I've done in Photoshop and Illustrator, generally for my Redbubble store or just as a manifestation of some spontaneous idea.
  
  <p><a href="misc.html">See Miscellaneous Work ></a></p>
  
stories: >
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/funding.png" alt="Instagram Story Sheet" style="width: 45%;"/>
  <img src="/assets/img/portfolio/funding2.png" align="right" alt="Instagram Story Sheet" style="width: 45%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/funding3.png" alt="Instagram Story Sheet" style="width: 45%;"/>
  <img src="/assets/img/portfolio/funding4.png" align="right" alt="Instagram Story Sheet" style="width: 45%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/funding5.png" alt="Instagram Story Sheet" style="width: 45%;"/>
  
dorms: >
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/baker.png" alt="Baker House" style="width: 45%;"/>
  <img src="/assets/img/portfolio/butterfield.png" align="center" alt="Butterfield House" style="width: 45%;"/>
  
  <img src="/assets/img/portfolio/brett.png" alt="Brett House" style="width: 45%;"/>
  <img src="/assets/img/portfolio/brooks.png" align="center" alt="Brooks House" style="width: 45%;"/>
  
  <img src="/assets/img/portfolio/chadbourne.png" alt="Chadbourne House" style="width: 45%;"/>
  <img src="/assets/img/portfolio/greenough.png" align="center" alt="Greenough House" style="width: 45%;"/>
  
  <img src="/assets/img/portfolio/johnson.png" alt="Johnson House" style="width: 45%;"/>
  <img src="/assets/img/portfolio/thatcher.png" align="center" alt="Thatcher House" style="width: 45%;"/>
  
  <img src="/assets/img/portfolio/vanmeter.png" alt="Van Meter House" style="width: 45%;"/>
  <img src="/assets/img/portfolio/wheeler.png" align="center" alt="Wheeler House" style="width: 45%;"/>
  
  <img src="/assets/img/portfolio/JQA.png" align="right" alt="John Quincy Adams Tower" style="width: 20%;"/>
  <img src="/assets/img/portfolio/coolidge.png" align="right" alt="Coolidge Tower" style="width: 20%;"/>
  <img src="/assets/img/portfolio/johnadams.png" align="right" alt="John Adams Tower" style="width: 20%;"/>
  <img src="/assets/img/portfolio/kennedy.png" align="right" alt="Kennedy Tower" style="width: 20%;"/>
  <img src="/assets/img/portfolio/washington.png" align="right" alt="Washington Tower" style="width: 20%;"/>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
drawings: >
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/goessmann.png" align="center" alt="A drawing of Goessmann Laboratory at UMass" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/bakerdrawing.png" align="center" alt="A drawing of Baker House at UMass" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/studentunion.png" align="center" alt="A drawing of the Student Union at UMass" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/butterfielddrawing.png" align="center" alt="A drawing of Butterfield House at UMass" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/librarydrawing.png" align="left" alt="A drawing of the Du Bois Library at UMass" style="width: 45%;"/>
  
  <img src="/assets/img/portfolio/shirtdesigncontest.png" align="right" alt="Entry for a T-Shirt Design Contest" style="width: 45%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
sga: >
  <p class="lead" style="font-variant:small-caps">
  </p>

  <img src="/assets/img/portfolio/sgaelectionsad.png" align="center" alt="A poster advertising a ballot initiative" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/ucardposter.png" align="center" alt="An Instagram story advertising the SGA election" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/elections.png" align="center" alt="An Instagram ad for a position with UMass SGA" style="width: 100%;"/>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/poster.png" align="center" alt="A poster advertising a supplementary meal program" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/splash.png" align="center" alt="An intro slide for a green initiative" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/wallet2.png" align="center" alt="A mockup for a ballot initiative" style="width: 100%;"/>
  
misc: >
  <p class="lead" style="font-variant:small-caps">
  </p>

  <img src="/assets/img/portfolio/helvumb.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/umasssign.png" align="center" alt="A digital drawing of the welcome sign at UMass" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/michiganunion.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/pantone.png" align="center" alt="" style="width: 100%;"/>

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/helvuconn.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/helvumass.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/gradientwhite.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/chapel.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/portfolio/homepage5.png" align="center" alt="" style="width: 100%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

#-------------------------------
# Work Section

projects:
- {name: ' ', folder: 'proj-4', file: 'projects/umasstour.html'}
- {name: ' ', folder: 'proj-1', file: 'projects/beton.html'}
- {name: ' ', folder: 'proj-2', file: 'projects/ub.html'}
- {name: ' ', folder: 'proj-3', file: 'projects/uca.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/adamlechowicz'}
- {icon: 'instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'envelope', link: 'mailto:adamlechowicz921@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
