#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'pages/projects.html'}
- {name: 'Portfolio', url: 'pages/portfolio.html'}
- {name: 'Résumé', url: 'pages/blog.html'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a Computer Science and Political Science student at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <img src="/assets/img/bio-photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%;"/>
  <img src="/assets/img/500x300.png" align="right" alt="Old Chapel at UMass Amherst" style="width: 45.2%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  Driven Computer Science and Political Science student at the University of Massachusetts Amherst. Excited about the intersectionality of Computer Science and Politics to create a better world. Especially interested in AI and machine learning ethics, data privacy, mobile computing, and human interface design, as well as advocacy around social, racial, educational, and environmental justice. 

contact: >
  # Contact

  You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.
 
portfolio: >
  A selected collection of my graphic design and UI work.

  #### @umass Instagram Story Funding Sheets

  <img src="/assets/img/portfolio/funding3.png" alt="Instagram Story Sheet" style="width: 45%;"/>
  <img src="/assets/img/portfolio/funding5.png" align="right" alt="Instagram Story Sheet" style="width: 45%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  A collection of informational sheets published on the @umass Instagram story in February 2020.  Designed in harmony with university brand guidelines, I made use of a subtle gradient centered on the university maroon color, in conjunction with the official typeface Frutiger and an assortment of background patterns to create sheets that are clearly related, but not entirely monotonous and "cookie-cutter". 

  #### UMass Dorm Icons

  An assortment of simple, distilled icons that depict dormitory buildings on the UMass Amherst campus.  Designing these, I constrained myself by using a low-res pixel art format, shedding extraneous features and focusing on distinctive features that make each building recognizable.  After a base image constructed in pixel-art, I scaled up the image to add color, shadow, and replace jagged roofline edges with smooth diagonal lines, resulting in crisp, simple icons.

  #### Student Government Association Work

  Loosely organized work that I've completed for the Student Government Association throughout my tenure as a Senator and Secretary of Technology.

  #### Drawings

  A small collection of detailed drawings of locations across the UMass campus, completed digitally in Photoshop.

  #### Miscellaneous Work

  Some additional, completely unorganized work that I've done in Photoshop and Illustrator, generally for my Redbubble store or just as a manifestation of some spontaneous idea. 

#-------------------------------
# Work Section

projects:
- {name: 'Beton3', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'UMass BRUT', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: ' ', folder: 'proj-3', file: 'projects/proj-3.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/adam-lechowicz-58703a154/'}
- {icon: 'twitter', link: 'https://twitter.com/adamlechowicz'}
- {icon: 'instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'envelope', link: 'mailto:adamlechowicz921@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
