#-------------------------------
# General Site Settings

menu:
# - {name: 'Publications', url: '#publications'}
- {name: 'Projects', url: 'pages/projects.html'}
- {name: 'CV', url: 'AdamLechowiczCurriculumVitae.pdf'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a computer science doctoral student at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'
  og:image: '/assets/img/5x3.jpeg'
  og:description: 'Adam Lechowicz is a computer science doctoral student at the University of Massachusetts Amherst.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-135296285-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <a href="https://www.umass.edu"><img src="/assets/img/5x3.jpeg" align="right" alt="Campus of UMass Amherst" style="width: 47.8%;"/></a>
  <img src="/assets/img/bio_photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%;"/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  #### Adam Lechowicz
  
  I am a first-year PhD student in the [Manning College of Information and Computer Sciences](https://www.cics.umass.edu) at the University of Massachusetts Amherst.  I'm excited about applications of computing that serve the public good.  I’m interested in studying how to build robust automated systems that can perform useful tasks with minimal human intervention.  I'm particularly interested in tackling problems with potential future applications serving a societal interest.  In the context of societal inequities, I'm also particularly interested in designing these systems with inbuilt constraints that prevent undesirable behavior and misuse, while ideally helping to alleviate inequalities.
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  Through my research, I strive to advance ideals of social, racial, economic, and environmental justice. 
  
  <p class="lead" id="publications" style="font-variant:small-caps">
  </p>
  
  #### Publications
  
  **[FlowSense: Monitoring Airflow in Building Ventilation Systems Using Audio Sensing](https://dl.acm.org/doi/10.1145/3517258)**  <br/>
  Bhawana Chhaglani, Camellia Zakaria, Adam Lechowicz, Jeremy Gummeson, Prashant Shenoy  <br/>
  ACM IMWUT'22.  
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[Local Edge Dynamics and Opinion Polarization](https://arxiv.org/abs/2111.14020)**  <br/>
  Nikita Bhalla, Adam Lechowicz, Cameron Musco  <br/>
  
  #### Contact
  
  email: alechowicz [at] umass [dot] edu    <br/>
  
#-------------------------------
# Work Section

projects:
- {name: ' ', folder: 'proj-5', file: 'projects/backtrack.html'}
- {name: ' ', folder: 'proj-2', file: 'projects/urv.html'}
- {name: ' ', folder: 'proj-4', file: 'projects/umasstour.html'}
- {name: ' ', folder: 'proj-1', file: 'projects/beton.html'}
- {name: ' ', folder: 'proj-3', file: 'projects/uca.html'}
# - {name: ' ', folder: 'port', file: 'pages/portfolio.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/adamlechowicz'}
- {icon: 'instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'envelope', link: 'mailto:alechowicz@umass.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
