#-------------------------------
# General Site Settings

menu:
- {name: 'Research', url: 'publications'}
# - {name: 'Projects', url: 'pages/projects.html'}
- {name: 'CV', url: 'AdamLechowiczCurriculumVitae.pdf'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a computer science doctoral student at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'
  og:image: '/assets/img/5x3nrel.jpeg'
  og:description: 'Adam Lechowicz is a computer science doctoral student at the University of Massachusetts Amherst.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-135296285-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <a href="https://www.umass.edu"><img src="/assets/img/5x3.jpeg" align="right" alt="Campus of UMass Amherst" style="width: 47.8%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"/></a> 
  <!-- <a href="https://www.nrel.gov"><img src="/assets/img/5x3nrel.jpeg" align="right" alt="ESIF Building at the National Renewable Energy Laboratory" style="width: 47.8%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"/></a> -->
  <img src="/assets/img/bio_photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%; border-radius: 25px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);"/>
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  #### Adam Lechowicz
  
  ***he/they***
  
  <p class="small" style="font-variant:small-caps">
  </p>

  I am a third-year Ph.D. student in the [Manning College of Information and Computer Sciences](https://www.cics.umass.edu) at the University of Massachusetts Amherst, advised by [Mohammad Hajiesmaili](https://groups.cs.umass.edu/hajiesmaili/) and [Prashant Shenoy](https://people.cs.umass.edu/~shenoy/index.html).  
  
  <p class="small" style="font-variant:small-caps">
  </p>

  <p style="text-align:center; font-weight: bolder; font-size: 16px;"><i> sustainability for computing, computing for sustainability </i></p>

  <p class="small" style="font-variant:small-caps">
  </p>
  
  I work at the intersection of theory and systems, with an emphasis on problems that hold implications for energy, equity, and climate change.  From a theoretical perspective, I am interested in designing algorithms for online optimization, particularly of the learning-augmented or provably fair types.  On the application side, I am especially interested in efforts which promote the decarbonization of energy systems and computing infrastructure. My work is supported by a [U.S. Department of Energy Computational Science Graduate Fellowship (CSGF)](https://www.krellinst.org/csgf/about-doe-csgf).

  <p class="small" style="font-variant:small-caps">
  </p>

  In Summer 2024, I worked with [Joshua Comden](https://research-hub.nrel.gov/en/persons/joshua-comden) at the [National Renewable Energy Laboratory](https://www.nrel.gov) on incentives and human-driven uncertainties in energy systems.  
  Before my Ph.D., I completed my undergraduate thesis with [Cameron Musco](https://people.cs.umass.edu/~cmusco/), studying polarization in social networks.

  <p class="small" style="font-variant:small-caps">
  </p>
  
  <p style="margin-bottom: 5px !important;">Through my research, I strive to advance ideals of social, racial, economic, and environmental justice.</p>

  <p class="small" style="font-variant:small-caps">
  </p>
  
  email: alechowicz [at] umass [dot] edu

  <div style="display: flex;">
  <div>
    <h4 id="selected-publications" style="margin-bottom:0.5em;">Selected Publications</h4>
  </div>
  <em style="margin-top: auto; margin-left: auto; margin-bottom: 0.85em; margin-right: 0.75em;"><a href="publications.html">full list →&nbsp;</a></em>
  </div>

  **[Chasing Convex Functions with Long-term Constraints](https://arxiv.org/abs/2402.14012)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Bo Sun, Noman Bashir, <span class="more-authors" style="border-bottom: 1px dashed" title="" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '3 more authors' ? 'Mohammad Hajiesmaili, Adam&nbsp;Wierman, Prashant Shenoy' : '3 more authors'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">3 more authors</span> <br/>
  ICML 2024. ([workshop version](https://learning-augmented-algorithms.github.io/papers/sigmetrics24-lata-posters-paper4.pdf))

  <p class="lead" style="font-variant:small-caps">
  </p>

  **[Online Conversion with Switching Costs: *Robust and Learning-augmented Algorithms*](https://arxiv.org/abs/2310.20598)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Bo Sun, Noman Bashir, <span class="more-authors" style="border-bottom: 1px dashed" title="" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '3 more authors' ? 'Mohammad Hajiesmaili, Adam&nbsp;Wierman, Prashant Shenoy' : '3 more authors'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">3 more authors</span> <br/>  
  ACM SIGMETRICS / IFIP Performance 2024.
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[The Online Pause and Resume Problem: <br/> *Optimal Algorithms and An Application to Carbon-aware Load Shifting*](https://arxiv.org/abs/2303.17551)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Jinhang Zuo, Noman Bashir, <span class="more-authors" style="border-bottom: 1px dashed" title="" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '3 more authors' ? 'Mohammad Hajiesmaili, Adam&nbsp;Wierman, Prashant Shenoy' : '3 more authors'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">3 more authors</span> <br/>
  ACM SIGMETRICS / IFIP Performance 2024.
  
  <p class="lead" style="font-variant:small-caps">
  </p>

  **[Time Fairness in Online Knapsack Problems](https://arxiv.org/abs/2305.13293)**  <br/>
  Adam Lechowicz, Rik Sengupta, Bo Sun, Shahin Kamali, Mohammad Hajiesmaili <br/>
  ICLR 2024. ([workshop version](https://learning-augmented-algorithms.github.io/2023/papers/sigmetrics23-lata-posters-paper8.pdf))

  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[Equitable Network-aware Decarbonization of Residential Heating at City Scale](https://arxiv.org/abs/2301.04747)**  <br/>
  Adam Lechowicz, Noman Bashir, John Wamburu, Mohammad Hajiesmaili, Prashant Shenoy  <br/>
  ACM e-Energy 2023. ([slides](https://drive.google.com/file/d/15THywHT1sZXHZGaaIW3LfboftIIu1gnj/view?usp=sharing))

  #### News

  - **(September 3rd, 2024)** I am at the [Seventh Workshop on Autonomous Energy Systems](https://www.nrel.gov/grid/seventh-workshop-autonomous-energy-systems.html) in Golden, CO to present my work on incentives in distribution grids.  
  
  - **(August 14th, 2024)** I am giving an invited talk at the SODALab group meeting at the University of Alberta.  See my slides [here](https://drive.google.com/file/d/1pCdYPfICf6RjwDLs0dSva6TVrVWREaFc/view?usp=sharing).  
  
  - **(July 21, 2024)** We have a paper at ICML 2024 on [convex function chasing with long-term constraints](https://openreview.net/forum?id=hRBdOHVn7y).  
  
  - **(June 18, 2024)** Excited to spend a summer at the [National Renewable Energy Laboratory’s Power Systems Engineering Center](https://www.nrel.gov/grid/) for my [DOE CSGF](https://www.krellinst.org/csgf/about-doe-csgf) practicum.  
  
  - **(June 12, 2024)** I am at ACM SIGMETRICS / IFIP Performance in Venice, Italy this week!  We have [two](https://dl.acm.org/doi/abs/10.1145/3626776) [papers](https://dl.acm.org/doi/abs/10.1145/3673660.3655074) in the Sustainable Computing session on (learning-augmented) online algorithms for carbon-aware data centers and EV charging, and I will also be giving a talk at the [LATA workshop](https://learning-augmented-algorithms.github.io).  
  
  - **(June 5, 2024)** We have a paper at ACM e-Energy 2024 on [carbon-aware resource scaling in data centers](https://dl.acm.org/doi/10.1145/3632775.3661942).
  

#-------------------------------
# Work Section

projects:
- {name: ' ', folder: 'proj-6', file: 'projects/venti.html'}
- {name: ' ', folder: 'proj-5', file: 'projects/backtrack.html'}
# - {name: ' ', folder: 'proj-2', file: 'projects/urv.html'}
- {name: ' ', folder: 'proj-7', file: 'projects/umasstour.html'}
- {name: ' ', folder: 'proj-1', file: 'projects/beton.html'}
- {name: ' ', folder: 'proj-3', file: 'projects/uca.html'}
# - {name: ' ', folder: 'port', file: 'pages/portfolio.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'fa-brands fa-google-scholar', link: 'https://scholar.google.com/citations?user=fZ2-jm0AAAAJ&hl=en&oi=ao'}
- {icon: 'fa-brands fa-linkedin-in', link: 'https://www.linkedin.com/in/adamlechowicz'}
- {icon: 'fa-brands fa-instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'fa-brands fa-x-twitter', link: 'https://x.com/adamlechowicz/'}
- {icon: 'fa-brands fa-github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'fa-solid fa-envelope', link: 'mailto:alechowicz@umass.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
