#-------------------------------
# General Site Settings

menu:
- {name: 'Publications', url: '#publications'}
- {name: 'Projects', url: 'pages/projects.html'}
- {name: 'CV', url: 'AdamLechowiczCurriculumVitae.pdf'}
# - {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Adam Lechowicz is a computer science doctoral student at the University of Massachusetts Amherst.'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'
  og:image: '/assets/img/5x3.jpeg'
  og:description: 'Adam Lechowicz is a computer science doctoral student at the University of Massachusetts Amherst.'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-135296285-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  <a href="https://www.umass.edu"><img src="/assets/img/5x3.jpeg" align="right" alt="Campus of UMass Amherst" style="width: 47.8%;"/></a>
  <img src="/assets/img/bio_photo.jpeg" alt="Photo of Adam Lechowicz" style="width: 33%;"/>
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  #### Adam Lechowicz
  
  ***he/they***
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  I am a first-year PhD student in the [Manning College of Information and Computer Sciences](https://www.cics.umass.edu) at the University of Massachusetts Amherst, where I am advised by [Mohammad Hajiesmaili](https://groups.cs.umass.edu/hajiesmaili/) and [Prashant Shenoy](https://people.cs.umass.edu/~shenoy/index.html).  
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  I work at the intersection of theory and systems, with an emphasis on problems that hold implications for energy, equity, and climate change.  From a theoretical perspective, I am interested in designing algorithms for online optimization, particularly of the learning-augmented or provably fair types.  On the application side, I am especially interested in efforts which promote the decarbonization of energy systems and computing infrastructure.
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  Through my research, I strive to advance ideals of social, racial, economic, and environmental justice.
  
  <p class="lead" id="publications" style="font-variant:small-caps">
  </p>
  
  #### Publications
  
  **[The Online Pause and Resume Problem: Optimal Algorithms and An Application to Carbon-Aware Load Shifting](https://arxiv.org/abs/2303.17551)**  <br/>
  Adam Lechowicz, Nicolas Christianson, Jinhang Zuo, Noman Bashir, Mohammad Hajiesmaili, Adam Wierman, Prashant Shenoy, <span class="more-authors" style="border-bottom: 1px dashed;" title="click to view 1 more author" onclick=" var element=$(this); element.attr('title', ''); var more_authors_text=element.text() == '1 more author...' ? 'Prashant Shenoy' : '1 more author...'; var cursorPosition=0; var textAdder=setInterval(function(){ element.text(more_authors_text.substring(0, cursorPosition + 1)); if (++cursorPosition == more_authors_text.length){ clearInterval(textAdder); } }, '10'); ">1 more author...</span>  <br/>
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[Equitable Network-Aware Decarbonization of Residential Heating at City Scale](https://arxiv.org/abs/2301.04747)**  <br/>
  Adam Lechowicz, Noman Bashir, John Wamburu, Mohammad Hajiesmaili, Prashant Shenoy  <br/>
  ACM e-Energy 2023, to appear.
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[Local Edge Dynamics and Opinion Polarization](https://arxiv.org/abs/2111.14020)**  <br/>
  Nikita Bhalla, Adam Lechowicz, Cameron Musco  <br/>
  ACM WSDM 2023. ([Slides](https://drive.google.com/file/d/1-4MGgvfCO8j_KpKpoNZEjdSCyPbE3IvX/view?usp=share_link), [Recorded Talk](https://dl.acm.org/doi/10.1145/3539597.3570442))
  
  <p class="lead" style="font-variant:small-caps">
  </p>
  
  **[FlowSense: Monitoring Airflow in Building Ventilation Systems Using Audio Sensing](https://arxiv.org/abs/2202.11136)**  <br/>
  Bhawana Chhaglani, Camellia Zakaria, Adam Lechowicz, Jeremy Gummeson, Prashant Shenoy  <br/>
  ACM IMWUT Vol. 6, March 2022.  
  
  #### Contact
  
  email: alechowicz [at] umass [dot] edu
  
  <p class="small" style="font-variant:small-caps">
  </p>
  
  *I am serving as the Student Trustee for the Amherst campus on the [UMass Board of Trustees](https://www.umassp.edu/bot) -- please contact me at [studenttrustee@umass.edu](mailto:studenttrustee@umass.edu) for policy and advocacy matters.*
  
#-------------------------------
# Work Section

projects:
- {name: ' ', folder: 'proj-6', file: 'projects/venti.html'}
- {name: ' ', folder: 'proj-5', file: 'projects/backtrack.html'}
- {name: ' ', folder: 'proj-2', file: 'projects/urv.html'}
- {name: ' ', folder: 'proj-7', file: 'projects/umasstour.html'}
- {name: ' ', folder: 'proj-1', file: 'projects/beton.html'}
- {name: ' ', folder: 'proj-3', file: 'projects/uca.html'}
# - {name: ' ', folder: 'port', file: 'pages/portfolio.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/adamlechowicz'}
- {icon: 'instagram', link: 'https://www.instagram.com/adamlechowicz/'}
- {icon: 'github', link: 'https://github.com/adamlechowicz/'}
- {icon: 'envelope', link: 'mailto:alechowicz@umass.edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
